### ISSUE TITLE
Import Err On Controller Crashing Application 

### ISSUE THREAD

**Issue by nionata** [nionata/Bloom#13]
Looks like there is a mismatch with the controller name causing import errors. Consider replacing "name" with a real name like "auth".

```
node server.js
internal/modules/cjs/loader.js:605
    throw err;
    ^
Error: Cannot find module '../controllers/name.server.controller.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/nicholasionata/Dropbox/School/S19/CEN3031/Bloom/server/routes/name.server.routes.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/nicholasionata/Dropbox/School/S19/CEN3031/Bloom/server/config/express.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

**Comment by nionata** [comment]
Fixed in PR #14
